/* MELP Stage 2 - Token Implementation
 * Generated by: YZ_02 (Lexer Specialist)
 * Date: 15 Ocak 2026
 * Phase: 2.0 - Lexer Implementation
 * 
 * This module provides utility functions for token manipulation.
 * 
 * Note: token_type_name() is implemented in lexer_impl.c
 */

#include "token.h"
#include <string.h>

/* Token utility functions can be added here if needed */

