/* MELP Stage 2 - Code Generator Test Suite
 * Generated by: YZ_05 (Code Generation Specialist)
 * Date: 15 Ocak 2026
 * Phase: 5.0 - Code Generation Implementation
 * 
 * This test suite validates the LLVM IR code generator.
 * 
 * Test Coverage:
 * - Simple programs (literals, variables, arithmetic)
 * - Expressions (arithmetic, comparison, logical)
 * - Control flow (if-then-else, while loops)
 * - Functions (parameters, return values, calls)
 * - Integration (complex programs)
 * - Edge cases (empty functions, nested control flow)
 * 
 * Test Methodology:
 * 1. Parse source → AST
 * 2. Semantic analysis (validate AST)
 * 3. Code generation → .ll file
 * 4. Compile with llc → .s file
 * 5. Link with gcc → executable
 * 6. Run executable, check exit code
 */

#include "codegen.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/wait.h>
#include <unistd.h>

/* Test statistics */
static int tests_run = 0;
static int tests_passed = 0;
static int tests_failed = 0;

/* Color output */
#define COLOR_GREEN "\033[0;32m"
#define COLOR_RED "\033[0;31m"
#define COLOR_BLUE "\033[0;34m"
#define COLOR_RESET "\033[0m"

/* ============================================================================
 * TEST UTILITIES
 * ============================================================================ */

/* Execute a shell command and return exit status */
static int execute_command(const char* command) {
    int status = system(command);
    if (WIFEXITED(status)) {
        return WEXITSTATUS(status);
    }
    return -1;
}

/* Test assertion */
static void assert_test(int condition, const char* test_name, const char* message) {
    tests_run++;
    if (condition) {
        tests_passed++;
        printf(COLOR_GREEN "✅ PASS" COLOR_RESET ": %s\n", test_name);
    } else {
        tests_failed++;
        printf(COLOR_RED "❌ FAIL" COLOR_RESET ": %s - %s\n", test_name, message);
    }
}

/* Compile and run MELP code, check exit code */
static int compile_and_run(const char* source, const char* test_name) {
    char ll_file[512];
    char s_file[512];
    char exe_file[512];
    char command[2048];
    
    snprintf(ll_file, sizeof(ll_file), "/tmp/%s.ll", test_name);
    snprintf(s_file, sizeof(s_file), "/tmp/%s.s", test_name);
    snprintf(exe_file, sizeof(exe_file), "/tmp/%s", test_name);
    
    // Generate LLVM IR
    if (!generate_code_from_source(source, ll_file)) {
        printf("  Codegen error: %s\n", get_codegen_error());
        return -1;
    }
    
    // Compile with llc
    snprintf(command, sizeof(command), "llc %s -o %s 2>/dev/null", ll_file, s_file);
    if (execute_command(command) != 0) {
        printf("  LLC compilation failed\n");
        return -1;
    }
    
    // Link with gcc
    snprintf(command, sizeof(command), "gcc %s -o %s 2>/dev/null", s_file, exe_file);
    if (execute_command(command) != 0) {
        printf("  GCC linking failed\n");
        return -1;
    }
    
    // Run executable and get exit code
    int exit_code = execute_command(exe_file);
    
    // Clean up temporary files
    remove(ll_file);
    remove(s_file);
    remove(exe_file);
    
    return exit_code;
}

/* ============================================================================
 * TEST CASES - BASIC PROGRAMS
 * ============================================================================ */

/* Test 1: Simple return literal */
void test_return_literal() {
    const char* source = 
        "function main() as numeric\n"
        "    return 42\n"
        "end_function";
    
    int result = compile_and_run(source, "test_return_literal");
    assert_test(result == 42, "test_return_literal", "Expected exit code 42");
}

/* Test 2: Variable declaration with literal */
void test_var_decl_literal() {
    const char* source = 
        "function main() as numeric\n"
        "    numeric x = 100\n"
        "    return x\n"
        "end_function";
    
    int result = compile_and_run(source, "test_var_decl_literal");
    assert_test(result == 100, "test_var_decl_literal", "Expected exit code 100");
}

/* Test 3: Variable declaration without initializer */
void test_var_decl_no_init() {
    const char* source = 
        "function main() as numeric\n"
        "    numeric x\n"
        "    x = 55\n"
        "    return x\n"
        "end_function";
    
    int result = compile_and_run(source, "test_var_decl_no_init");
    assert_test(result == 55, "test_var_decl_no_init", "Expected exit code 55");
}

/* Test 4: Assignment */
void test_assignment() {
    const char* source = 
        "function main() as numeric\n"
        "    numeric x = 10\n"
        "    x = 20\n"
        "    return x\n"
        "end_function";
    
    int result = compile_and_run(source, "test_assignment");
    assert_test(result == 20, "test_assignment", "Expected exit code 20");
}

/* ============================================================================
 * TEST CASES - ARITHMETIC EXPRESSIONS
 * ============================================================================ */

/* Test 5: Addition */
void test_addition() {
    const char* source = 
        "function main() as numeric\n"
        "    return 10 + 5\n"
        "end_function";
    
    int result = compile_and_run(source, "test_addition");
    assert_test(result == 15, "test_addition", "Expected 10 + 5 = 15");
}

/* Test 6: Subtraction */
void test_subtraction() {
    const char* source = 
        "function main() as numeric\n"
        "    return 20 - 7\n"
        "end_function";
    
    int result = compile_and_run(source, "test_subtraction");
    assert_test(result == 13, "test_subtraction", "Expected 20 - 7 = 13");
}

/* Test 7: Multiplication */
void test_multiplication() {
    const char* source = 
        "function main() as numeric\n"
        "    return 6 * 7\n"
        "end_function";
    
    int result = compile_and_run(source, "test_multiplication");
    assert_test(result == 42, "test_multiplication", "Expected 6 * 7 = 42");
}

/* Test 8: Division */
void test_division() {
    const char* source = 
        "function main() as numeric\n"
        "    return 20 / 4\n"
        "end_function";
    
    int result = compile_and_run(source, "test_division");
    assert_test(result == 5, "test_division", "Expected 20 / 4 = 5");
}

/* Test 9: Modulo */
void test_modulo() {
    const char* source = 
        "function main() as numeric\n"
        "    return 17 % 5\n"
        "end_function";
    
    int result = compile_and_run(source, "test_modulo");
    assert_test(result == 2, "test_modulo", "Expected 17 % 5 = 2");
}

/* Test 10: Complex arithmetic */
void test_complex_arithmetic() {
    const char* source = 
        "function main() as numeric\n"
        "    numeric a = 5\n"
        "    numeric b = 10\n"
        "    numeric c = a + b * 2\n"
        "    return c\n"
        "end_function";
    
    int result = compile_and_run(source, "test_complex_arithmetic");
    assert_test(result == 25, "test_complex_arithmetic", "Expected 5 + 10*2 = 25");
}

/* Test 11: Negation */
void test_negation() {
    const char* source = 
        "function main() as numeric\n"
        "    numeric x = 10\n"
        "    return -x + 100\n"
        "end_function";
    
    int result = compile_and_run(source, "test_negation");
    assert_test(result == 90, "test_negation", "Expected -10 + 100 = 90");
}

/* ============================================================================
 * TEST CASES - COMPARISON EXPRESSIONS
 * ============================================================================ */

/* Test 12: Less than (true) */
void test_less_than_true() {
    const char* source = 
        "function main() as numeric\n"
        "    if 5 < 10 then\n"
        "        return 1\n"
        "    else\n"
        "        return 0\n"
        "    end_if\n"
        "end_function";
    
    int result = compile_and_run(source, "test_less_than_true");
    assert_test(result == 1, "test_less_than_true", "Expected 5 < 10 = true");
}

/* Test 13: Less than (false) */
void test_less_than_false() {
    const char* source = 
        "function main() as numeric\n"
        "    if 10 < 5 then\n"
        "        return 1\n"
        "    else\n"
        "        return 0\n"
        "    end_if\n"
        "end_function";
    
    int result = compile_and_run(source, "test_less_than_false");
    assert_test(result == 0, "test_less_than_false", "Expected 10 < 5 = false");
}

/* Test 14: Greater than */
void test_greater_than() {
    const char* source = 
        "function main() as numeric\n"
        "    if 10 > 5 then\n"
        "        return 1\n"
        "    else\n"
        "        return 0\n"
        "    end_if\n"
        "end_function";
    
    int result = compile_and_run(source, "test_greater_than");
    assert_test(result == 1, "test_greater_than", "Expected 10 > 5 = true");
}

/* Test 15: Equal */
void test_equal() {
    const char* source = 
        "function main() as numeric\n"
        "    if 7 == 7 then\n"
        "        return 1\n"
        "    else\n"
        "        return 0\n"
        "    end_if\n"
        "end_function";
    
    int result = compile_and_run(source, "test_equal");
    assert_test(result == 1, "test_equal", "Expected 7 == 7 = true");
}

/* Test 16: Not equal */
void test_not_equal() {
    const char* source = 
        "function main() as numeric\n"
        "    if 5 != 10 then\n"
        "        return 1\n"
        "    else\n"
        "        return 0\n"
        "    end_if\n"
        "end_function";
    
    int result = compile_and_run(source, "test_not_equal");
    assert_test(result == 1, "test_not_equal", "Expected 5 != 10 = true");
}

/* ============================================================================
 * TEST CASES - CONTROL FLOW (IF-THEN-ELSE)
 * ============================================================================ */

/* Test 17: If-then (condition true) */
void test_if_then_true() {
    const char* source = 
        "function main() as numeric\n"
        "    numeric x = 0\n"
        "    if 10 > 5 then\n"
        "        x = 42\n"
        "    end_if\n"
        "    return x\n"
        "end_function";
    
    int result = compile_and_run(source, "test_if_then_true");
    assert_test(result == 42, "test_if_then_true", "Expected x = 42");
}

/* Test 18: If-then (condition false) */
void test_if_then_false() {
    const char* source = 
        "function main() as numeric\n"
        "    numeric x = 0\n"
        "    if 5 > 10 then\n"
        "        x = 42\n"
        "    end_if\n"
        "    return x\n"
        "end_function";
    
    int result = compile_and_run(source, "test_if_then_false");
    assert_test(result == 0, "test_if_then_false", "Expected x = 0");
}

/* Test 19: If-then-else (take then) */
void test_if_else_then() {
    const char* source = 
        "function main() as numeric\n"
        "    numeric x\n"
        "    if 10 > 5 then\n"
        "        x = 100\n"
        "    else\n"
        "        x = 200\n"
        "    end_if\n"
        "    return x\n"
        "end_function";
    
    int result = compile_and_run(source, "test_if_else_then");
    assert_test(result == 100, "test_if_else_then", "Expected x = 100");
}

/* Test 20: If-then-else (take else) */
void test_if_else_else() {
    const char* source = 
        "function main() as numeric\n"
        "    numeric x\n"
        "    if 5 > 10 then\n"
        "        x = 100\n"
        "    else\n"
        "        x = 200\n"
        "    end_if\n"
        "    return x\n"
        "end_function";
    
    int result = compile_and_run(source, "test_if_else_else");
    assert_test(result == 200, "test_if_else_else", "Expected x = 200");
}

/* Test 21: Nested if statements */
void test_nested_if() {
    const char* source = 
        "function main() as numeric\n"
        "    numeric x = 0\n"
        "    if 10 > 5 then\n"
        "        if 20 > 15 then\n"
        "            x = 99\n"
        "        end_if\n"
        "    end_if\n"
        "    return x\n"
        "end_function";
    
    int result = compile_and_run(source, "test_nested_if");
    assert_test(result == 99, "test_nested_if", "Expected x = 99");
}

/* ============================================================================
 * TEST CASES - CONTROL FLOW (WHILE LOOPS)
 * ============================================================================ */

/* Test 22: While loop (count to 5) */
void test_while_count() {
    const char* source = 
        "function main() as numeric\n"
        "    numeric i = 0\n"
        "    while i < 5\n"
        "        i = i + 1\n"
        "    end_while\n"
        "    return i\n"
        "end_function";
    
    int result = compile_and_run(source, "test_while_count");
    assert_test(result == 5, "test_while_count", "Expected i = 5");
}

/* Test 23: While loop (sum 1 to 10) */
void test_while_sum() {
    const char* source = 
        "function main() as numeric\n"
        "    numeric sum = 0\n"
        "    numeric i = 1\n"
        "    while i <= 10\n"
        "        sum = sum + i\n"
        "        i = i + 1\n"
        "    end_while\n"
        "    return sum\n"
        "end_function";
    
    int result = compile_and_run(source, "test_while_sum");
    assert_test(result == 55, "test_while_sum", "Expected sum = 55");
}

/* Test 24: While loop (immediate exit) */
void test_while_immediate_exit() {
    const char* source = 
        "function main() as numeric\n"
        "    numeric x = 10\n"
        "    while x < 5\n"
        "        x = x + 1\n"
        "    end_while\n"
        "    return x\n"
        "end_function";
    
    int result = compile_and_run(source, "test_while_immediate_exit");
    assert_test(result == 10, "test_while_immediate_exit", "Expected x = 10");
}

/* ============================================================================
 * TEST CASES - FUNCTIONS
 * ============================================================================ */

/* Test 25: Simple function call */
void test_function_call_simple() {
    const char* source = 
        "function add(numeric a; numeric b) as numeric\n"
        "    return a + b\n"
        "end_function\n"
        "\n"
        "function main() as numeric\n"
        "    return add(10; 15)\n"
        "end_function";
    
    int result = compile_and_run(source, "test_function_call_simple");
    assert_test(result == 25, "test_function_call_simple", "Expected 10 + 15 = 25");
}

/* Test 26: Function with multiple parameters */
void test_function_multiple_params() {
    const char* source = 
        "function calculate(numeric a; numeric b; numeric c) as numeric\n"
        "    return a + b * c\n"
        "end_function\n"
        "\n"
        "function main() as numeric\n"
        "    return calculate(5; 10; 2)\n"
        "end_function";
    
    int result = compile_and_run(source, "test_function_multiple_params");
    assert_test(result == 25, "test_function_multiple_params", "Expected 5 + 10*2 = 25");
}

/* Test 27: Function calling another function */
void test_function_chain() {
    const char* source = 
        "function double(numeric x) as numeric\n"
        "    return x * 2\n"
        "end_function\n"
        "\n"
        "function triple(numeric x) as numeric\n"
        "    return x * 3\n"
        "end_function\n"
        "\n"
        "function main() as numeric\n"
        "    return double(triple(5))\n"
        "end_function";
    
    int result = compile_and_run(source, "test_function_chain");
    assert_test(result == 30, "test_function_chain", "Expected double(triple(5)) = 30");
}

/* Test 28: Recursive function (factorial) */
void test_factorial() {
    const char* source = 
        "function factorial(numeric n) as numeric\n"
        "    if n <= 1 then\n"
        "        return 1\n"
        "    else\n"
        "        return n * factorial(n - 1)\n"
        "    end_if\n"
        "end_function\n"
        "\n"
        "function main() as numeric\n"
        "    return factorial(5)\n"
        "end_function";
    
    int result = compile_and_run(source, "test_factorial");
    assert_test(result == 120, "test_factorial", "Expected factorial(5) = 120");
}

/* ============================================================================
 * TEST CASES - INTEGRATION (COMPLEX PROGRAMS)
 * ============================================================================ */

/* Test 29: Fibonacci sequence */
void test_fibonacci() {
    const char* source = 
        "function fib(numeric n) as numeric\n"
        "    if n <= 1 then\n"
        "        return n\n"
        "    else\n"
        "        return fib(n - 1) + fib(n - 2)\n"
        "    end_if\n"
        "end_function\n"
        "\n"
        "function main() as numeric\n"
        "    return fib(10)\n"
        "end_function";
    
    int result = compile_and_run(source, "test_fibonacci");
    assert_test(result == 55, "test_fibonacci", "Expected fib(10) = 55");
}

/* Test 30: Complex calculation with control flow */
void test_complex_calculation() {
    const char* source = 
        "function main() as numeric\n"
        "    numeric result = 0\n"
        "    numeric i = 1\n"
        "    while i <= 5\n"
        "        if i % 2 == 0 then\n"
        "            result = result + i * 2\n"
        "        else\n"
        "            result = result + i\n"
        "        end_if\n"
        "        i = i + 1\n"
        "    end_while\n"
        "    return result\n"
        "end_function";
    
    int result = compile_and_run(source, "test_complex_calculation");
    // 1 + (2*2) + 3 + (4*2) + 5 = 1 + 4 + 3 + 8 + 5 = 21
    assert_test(result == 21, "test_complex_calculation", "Expected result = 21");
}

/* Test 31: Multiple variables and operations */
void test_multiple_variables() {
    const char* source = 
        "function main() as numeric\n"
        "    numeric a = 10\n"
        "    numeric b = 20\n"
        "    numeric c = 30\n"
        "    numeric result = a + b - c\n"
        "    return result\n"
        "end_function";
    
    int result = compile_and_run(source, "test_multiple_variables");
    assert_test(result == 0, "test_multiple_variables", "Expected 10 + 20 - 30 = 0");
}

/* ============================================================================
 * MAIN TEST RUNNER
 * ============================================================================ */

int main() {
    printf("\n");
    printf(COLOR_BLUE "================================================\n" COLOR_RESET);
    printf(COLOR_BLUE "MELP Stage 2 - Code Generator Test Suite\n" COLOR_RESET);
    printf(COLOR_BLUE "YZ_05 - Phase 5.0\n" COLOR_RESET);
    printf(COLOR_BLUE "================================================\n" COLOR_RESET);
    printf("\n");
    
    // Run all tests
    printf("Running basic program tests...\n");
    test_return_literal();
    test_var_decl_literal();
    test_var_decl_no_init();
    test_assignment();
    
    printf("\nRunning arithmetic expression tests...\n");
    test_addition();
    test_subtraction();
    test_multiplication();
    test_division();
    test_modulo();
    test_complex_arithmetic();
    test_negation();
    
    printf("\nRunning comparison tests...\n");
    test_less_than_true();
    test_less_than_false();
    test_greater_than();
    test_equal();
    test_not_equal();
    
    printf("\nRunning control flow tests (if-then-else)...\n");
    test_if_then_true();
    test_if_then_false();
    test_if_else_then();
    test_if_else_else();
    test_nested_if();
    
    printf("\nRunning control flow tests (while loops)...\n");
    test_while_count();
    test_while_sum();
    test_while_immediate_exit();
    
    printf("\nRunning function tests...\n");
    test_function_call_simple();
    test_function_multiple_params();
    test_function_chain();
    test_factorial();
    
    printf("\nRunning integration tests...\n");
    test_fibonacci();
    test_complex_calculation();
    test_multiple_variables();
    
    // Print summary
    printf("\n");
    printf(COLOR_BLUE "================================================\n" COLOR_RESET);
    printf(COLOR_BLUE "TEST SUMMARY\n" COLOR_RESET);
    printf(COLOR_BLUE "================================================\n" COLOR_RESET);
    printf("Total tests run:    %d\n", tests_run);
    printf(COLOR_GREEN "Tests passed:       %d\n" COLOR_RESET, tests_passed);
    printf(COLOR_RED "Tests failed:       %d\n" COLOR_RESET, tests_failed);
    printf("Success rate:       %.1f%%\n", 
           tests_run > 0 ? (tests_passed * 100.0 / tests_run) : 0.0);
    printf(COLOR_BLUE "================================================\n" COLOR_RESET);
    printf("\n");
    
    // Return 0 for success, 1 for failure
    return (tests_failed == 0) ? 0 : 1;
}
